version: "2.0"

services:
  flaskserver:
    build: flaskserver
    ports:
      - 5000:5000
    depends_on:
      - redisdb
    environment:
      - ENV_HOST=database #Debe ser el mismo nombre que el alias de redisdb
      - ENV_PORT=6379
      - ENV_DB=0
    links:
      - "redisdb:database"

  redisdb:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      
  staticserver:
    build: nginx_static
    ports:
      - 8080:80
      
  proxy:
    build: nginx_proxy
    ports:
      - 80:80
    environment:
      - ENV_PORT=80
      - ENV_HOST=54.202.8.127
      - ENV_PYTHON_HOST=pythonapp
      - ENV_PYTHON_PORT=5000
    links:
      - "flaskserver:pythonapp"
      - "staticserver:nginxstatic"